Django Application/ml_app/urls.py
"""project_settings URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import about, index, predict_page,cuda_full

app_name = 'ml_app'
handler404 = views.handler404

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('predict/', predict_page, name='predict'),
    path('cuda_full/',cuda_full,name='cuda_full'),
]

Django Application/project_settings/urls.py
"""project_settings URL Configuration
"""
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ml_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django Application/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="/static/bootstrap/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
    <link rel="stylesheet" href="/static/css/jquery-ui.css">

    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <title>Deepfake Detection</title>
</head>
<body>
    {%include 'nav-bar.html'%}
    {%block content%}
    {%endblock%}
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script> -->
        <script src="/static/js/jquery-3.4.1.min.js" ></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script> -->
        <script src="/static/js/popper.min.js"></script>
    <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script> -->
        <script src="/static/js/jquery-ui.min.js"></script>
    
        {%block js_cripts%}
    {%endblock%}
    {%include 'footer.html'%}
</body>

</html>

Django Application/templates/footer.html
<footer class="footer">
    <div class="container">
      <center><span class="text-muted" >Copyright @ {%now 'Y'%}</span></center>
      <!-- <a href="{% url 'ml_app:home'%}">Home</a>
      <a href="{% url 'ml_app:about'%}">About</a>
      <a href="#">Github Link</a> -->
    </div>
  </footer>

Django Application/templates/nav-bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'ml_app:home'%}">Home</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="{%url 'ml_app:about'%}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">GitHub</a>
            </li> -->
        </ul>
    </div>
</nav>